name: FTP Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: Deploy with Password
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy with Password
        uses: wlixcc/SFTP-Deploy-Action@v1.2.5
        with:
          username: ${{ secrets.FTP_USER }}
          server: ${{ secrets.FTP_HOST}}
          port: ${{ secrets.FTP_PORT }}
          password: ${{ secrets.FTP_PASS }}
          local_path: './'
          remote_path: './'
          sftp_only: true

      - name: Create Update Trigger Locally
        run: echo "triggering update" > update.trigger

      - name: Upload Update Trigger
        uses: wlixcc/SFTP-Deploy-Action@v1.2.5
        with:
          username: ${{ secrets.FTP_USER }}
          server: ${{ secrets.FTP_HOST }}
          port: ${{ secrets.FTP_PORT }}
          password: ${{ secrets.FTP_PASS }}
          local_path: 'update.trigger'
          remote_path: './'
          sftp_only: true
